config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  resources :colors
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/color.rb
class Color < ApplicationRecord
  validates :name, uniqueness: true, length: { maximum: 15 }, presence: true
  validates :description, length: { maximum: 145 }, presence: true
  validates :hex, format: { with: /\A([A-Fa-f0-9]{6})\z/ }, presence: true
  validates :rgb, format: { with: /\A(\d{1,3}), (\d{1,3}), (\d{1,3})\z/ }, presence: true
  validates :hsl, format: { with: /\A(\d{1,3}), (\d{1,3}(.\d{1})?%), (\d{1,3}(.\d{1})?%)\z/ }, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :success
end

app/controllers/colors_controller.rb
class ColorsController < ApplicationController
  before_action :set_color, only: %i[show edit update destroy]
  def index
    @colors = Color.all.order(name: :asc)
  end

  def new
    @color = Color.new
  end

  def create
    @color = Color.new(color_params)
    if @color.save
      redirect_to color_url(@color), success: 'Color successfully added.'
    else
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    if @color.update(color_params)
      redirect_to color_url(@color), success: 'Color successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    deleted_color = @color.destroy
    redirect_to colors_url, success: "Color #{deleted_color[:name].inspect} has been successfully deleted."
  end

  private

  def color_params
    params.require(:color).permit(:name, :description, :rgb, :hex, :hsl)
  end

  def set_color
    @color = Color.find(params[:id])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(title = '')
    initial_title = 'Color Collection'
    if title.empty?
      initial_title
    else
      "#{title} | #{initial_title}"
    end
  end

  def format_auxiliary_verb(count)
    count == 1 ? 'is' : 'are'
  end
end

app/helpers/colors_helper.rb
module ColorsHelper

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/colors/edit.html.erb
<% provide(:title, "Edit Color") %>
<% provide(:color_submit_text, "Update color")%>
<%= render 'shared/color_form' %>

app/views/colors/index.html.erb
<% provide(:title, "Colors") %>
<div class="h-[calc(100%-88px)] bg-slate-600 p-4 overflow-auto">
  <h1 class="text-5xl font-bold text-white text-center"><%= yield(:title) %></h1>
  <%= render 'shared/success_flash'%>
  <div class="flex gap-6 flex-wrap bg-slate-700 rounded-md p-6 w-fit m-auto mt-6 justify-around text-slate-200">
    <% if @colors.count > 0 %>
      <% @colors.each do |color| %>
        <div class="flex flex-col justify-center items-center">
          <div class="h-32 w-32 rounded-md" style="background-color: #<%= color.hex %>" ></div>
          <%= link_to color[:name], color, class: "text-lg hover:underline"%>
        </div>
      <% end %>
    <% else %>
      <p class="text-2xl font-semibold text-center">There are no colors stored currently.</p>
    <% end %>
  </div>
</div>

app/views/colors/new.html.erb
<% provide(:title, "Add Color") %>
<% provide(:color_submit_text, "Submit") %>
<%= render 'shared/color_form' %>

app/views/colors/show.html.erb
<% provide(:title, @color.name)%>
<div class="h-[calc(100%-88px)] bg-slate-600 text-slate-200 p-4 overflow-auto">
  <h1 class="text-5xl font-bold text-white text-center"><%= yield(:title) %></h1>
  <%= render 'shared/success_flash'%>
  <div class="flex flex-col items-center justify-center bg-slate-700 rounded-md p-6 sm:w-fit m-auto my-6">
    <div class="flex flex-col gap-4">
      <div class="flex gap-6 items-center">
        <div class=" h-36 w-36 sm:h-48 sm:w-48 rounded-md" style="background-color: #<%= @color.hex %>"></div>
        <div class="flex flex-col w-32 sm:w-48 break-words">
          <p class="font-bold text-xl">Description:</p>
          <p><%= @color.description %></p>
        </div>
      </div>
      <h1 class="font-bold m-auto text-2xl">Color Codes</h1>
      <div class="grid grid-cols-2 justify-items-center text-xl">
        <p class="font-bold col-span-2 sm:col-span-1">HEX: <span class="font-medium">#<%= @color.hex %></span></p>
        <p class="font-bold col-span-2 sm:col-span-1">RGB: <span class="font-medium">(<%= @color.rgb %>)</span></p>
        <p class="font-bold col-span-2">HSL: <span class="font-medium">(<%= @color.hsl %>)</span></p>
      </div>
    </div>
    <div class="mt-6">
      <%= link_to "Edit Color", edit_color_path, class: "bg-slate-300 text-slate-800 text-lg rounded-md px-4 py-2 mr-2 font-medium cursor-pointer hover:ring-2 ring-slate-400" %>
      <%= link_to "Delete Color", @color, method: :delete, data: { confirm: "Are you sure you want to delete this color?" }, class: "bg-slate-300 text-slate-800 text-lg rounded-md px-4 py-2 font-medium cursor-pointer hover:ring-2 ring-slate-400" %>
    </div>
  </div>
</div>

app/views/layouts/_color_error_msg.html.erb
<% if @color.errors.any? %>
  <div class="bg-slate-700 flex w-fit rounded border-2 border-red-400 m-auto mt-6">
    <div class="w-20 bg-red-400 text-xl flex justify-center items-center p-6">
      <div class="border-2 rounded-full p-4 h-12 w-12 flex justify-center items-center border-slate-300 text-slate-300">X</div>
    </div>
    <div class="p-4 text-slate-300">
      <p class="font-medium text-lg">There <%= format_auxiliary_verb(@color.errors.count) %> <%= pluralize(@color.errors.count, "error").upcase%> in your submission. </p>
      <ul class="list-disc list-inside">
        <% @color.errors.full_messages.each do |message| %>
          <li> <%= message %>. </li>
        <%end%>
      </ul>
    </div>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class ="h-6 bg-slate-700 flex justify-center items-center gap-6 text-slate-200 font-medium">
  <p>Created by: reyolan</p>
  <%= link_to "Github", "https://github.com/reyolan", class: "hover:text-slate-400" %>
</footer>

app/views/layouts/_navigation.html.erb
 <nav class="flex justify-between items-center h-16 px-5 md:px-16 w-full bg-slate-700 relative">
  <%= link_to root_path, class: "text-white text-xl sm:text-2xl font-bold sm:w-auto w-fit" do %>
    <div class="flex gap-3 items-center ">
      <%= image_tag "logo.png", class: "w-10" %>
      <p>COLOR COLLECTION</p>
    </div>
  <% end %>
  <span id="hamburger" class="sm:hidden text-white text-lg font-bold">&#9776;</span>
  <ul id="list" class="hidden gap-0 flex flex-col absolute top-0 rounded right-0 mt-16 px-4 py-2 bg-slate-700 text-right sm:mr-0 sm:text-left sm:mt-0 sm:flex-row sm:gap-4 sm:flex sm:static">
    <li><%= link_to "Home", root_path, class: "text-lg text-slate-200 hover:text-slate-400 font-medium" %></li>
    <li><%= link_to "Colors", colors_path, class: "text-lg text-slate-200 hover:text-slate-400 font-medium" %></h1>
    <li><%= link_to "Add Color", new_color_path, class: "text-lg text-slate-200 hover:text-slate-400 font-medium" %></h1>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title))%></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= vite_client_tag %>
    <%= favicon_link_tag 'logo.png'%>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= vite_typescript_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="h-screen">
      <%= render 'layouts/navigation'%>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/shared/_color_form.html.erb
<div class="h-[calc(100%-88px)] bg-slate-600 text-slate-200 p-4 overflow-auto" data-color-form = "">
  <h1 class="text-5xl font-bold text-white text-center"> <%= yield(:title) %> </h1>
  <%= render 'layouts/color_error_msg' %>
  <div class="flex flex-col items-center justify-center bg-slate-700 rounded-md p-6 sm:w-fit m-auto gap-6 mt-6">
    <input type="color" data-color="" class="m-auto h-32 w-32 rounded bg-slate-400 cursor-pointer">
    <%= form_with model: @color do |form| %>
      <div class= "flex flex-col sm:flex-row justify-center gap-8">
        <div>
          <div class="flex flex-col mb-2">
            <%= form.label :name, "Name:", class: 'text-lg' %>
            <%= form.text_field :name, class: 'text-slate-800 rounded px-1'%>
          </div>
          <div class="flex flex-col">
            <%= form.label :description, "Description:", class:''%>
            <%= form.text_area :description, class: 'text-slate-800 rounded px-1 resize-none'%>
          </div>
        </div>
        <div class="flex flex-col gap-2">
          <div class="flex flex-col">
            <%= form.label :hex, "HEX: #", class: 'pointer-events-none' %>
            <%= form.text_field :hex, readonly: true, class: ' text-slate-800 rounded pointer-events-none px-1' %>
          </div>
          <div class="flex flex-col">
            <%= form.label :rgb, "RGB:", class: 'pointer-events-none' %>
            <%= form.text_field :rgb, readonly: true, class: ' text-slate-800 rounded pointer-events-none px-1' %>
          </div>
          <div class="flex flex-col">
            <%= form.label :hsl, "HSL: ", class: 'pointer-events-none' %>
            <%= form.text_field :hsl, readonly: true, class: ' text-slate-800 rounded pointer-events-none px-1' %>
          </div>
        </div>
      </div>
      <div class="flex justify-center">
        <%= form.submit yield(:color_submit_text), class: 'bg-slate-300 text-slate-800 text-xl rounded-md mt-6 px-6 py-2 font-medium cursor-pointer hover:ring-2 ring-slate-400'%>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_success_flash.html.erb
<% if flash[:success] %>
  <div class="bg-slate-700 flex w-fit rounded border-2 border-green-400 m-aut m-auto my-6">
    <div class="w-20 bg-green-400 text-xl flex justify-center items-center p-6">
      <div class="border-2 rounded-full p-4 h-12 w-12 flex justify-center items-center border-white text-white">&#10003;</div>
    </div>
    <div class="p-4 flex flex-col justify-center text-slate-300">
      <p class="font-medium text-xl">SUCCESS</p>
      <p class="text-lg"> <%= flash[:success] %></p>
    </div>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<div class="flex flex-col items-center h-[calc(100%-88px)] justify-center gap-5 bg-slate-600 p-6">
  <h1 class="font-bold  text-6xl md:text-8xl text-slate-100 text-center select-none"> Color Collection </h1>
  <h2 class="font-medium text-2xl md:text-4xl text-slate-100 text-center select-none"> A collection of desirable colors in CSS </h2>
  <div class="flex gap-8">
    <%= link_to "See all colors", colors_path, class: "text-2xl bg-slate-700 rounded-md text-white px-2 md:px-3.5 py-2 hover:ring-2 ring-slate-500 text-center" %>
    <%= link_to "Add color", new_color_path, class: "text-2xl bg-slate-700 rounded-md text-white px-2 md:px-3.5 py-2 hover:ring-2 ring-slate-500 text-center" %>
  </div>
</div>